"""Add size to cart items

Revision ID: 6085569ed925
Revises: 
Create Date: 2026-07-29 16:26:45.741016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6085569ed925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'size',
                sa.String(length=10),
                nullable=False,
                server_default='M'
            )
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
